# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Lemonade on NPU and Hybrid with OGA environment 🌩️

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      runson:
        description: 'Which runner group to run the workflow on'
        default: 'stx'
        required: true
        type: choice
        options:
        - 'stx'
        - 'stx-test'
      setup:
        description: 'Install miniforge to C:\Users\selfhost'
        default: false
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  test-npu-and-hybrid:
    env:
        LEMONADE_CI_MODE: "True"
    runs-on: ["${{ inputs.runson || 'stx' }}", 'Windows']
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      
      - name: Download and Install Miniforge
        shell: PowerShell
        if: ${{ inputs.setup }}
        run: |
          $ErrorActionPreference = "Stop"
          if (!(Test-Path -Path "C:\Users\selfhost")) { mkdir C:\Users\selfhost }
          Invoke-WebRequest -Uri "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe" -OutFile "miniforge3.exe"
          Start-Process -FilePath "miniforge3.exe" -ArgumentList "/S /InstallationType=JustMe /AddToPath=1 /RegisterPython=0 /D=C:\Users\selfhost\miniforge3" -Wait

      - name: Initialize Conda
        shell: PowerShell
        if: ${{ inputs.setup }}
        run: |
          $ErrorActionPreference = "Stop"
          Write-Host "Step 1: Add Conda to system PATH"
          $env:Path = "C:\Users\selfhost\miniforge3;C:\Users\selfhost\miniforge3\Scripts;$env:Path"
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)

          Write-Host "Step 2: Initialize conda for both shells"
          & "C:\Users\selfhost\miniforge3\Scripts\conda.exe" init powershell
          & "C:\Users\selfhost\miniforge3\Scripts\conda.exe" init cmd.exe
          
      - name: Create conda environment
        shell: PowerShell
        run: |
          # Make sure the system-level python is clean
          Remove-Item -Path "C:\\windows\\system32\\config\\systemprofile\\AppData\\Roaming\\Python" -Recurse -Force 
          
          $ErrorActionPreference = "Stop"

          # Keep conda up-to-date since they can apparently break things on the server side
          # We can probably remove this in the future
          conda update conda conda-libmamba-solver --solver classic
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

          conda create -p .\lemon-ryzenai-ci python=3.12 -y
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          
      - name: Install dependencies
        shell: PowerShell
        run: |
          $ErrorActionPreference = "Stop"
          
          conda run -p .\lemon-ryzenai-ci python -m pip install --upgrade pip
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          
          conda run -p .\lemon-ryzenai-ci conda install -y pylint
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          
          conda run -p .\lemon-ryzenai-ci python -m pip check
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          
          # Install using PyPI approach for v1.5.0+
          conda run -p .\lemon-ryzenai-ci pip install -e .[dev]
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          
          # Install ryzenai as a separate step to minimize use of pypi.amd.com
          conda run -p .\lemon-ryzenai-ci pip install -e .[oga-ryzenai] --extra-index-url https://pypi.amd.com/simple
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

          $cwd = (Get-Item .\).FullName
          echo "HF_HOME=$cwd\hf-cache" >> $Env:GITHUB_ENV

      - name: Run NPU tests
        shell: PowerShell
        env:
          HF_HOME: "${{ env.HF_HOME }}"
          LEMONADE_CACHE_DIR: ".\\ci-cache"
        run: |
          $ErrorActionPreference = "Stop"

          # Test CLI
          conda run -p .\lemon-ryzenai-ci lemonade -i amd/Llama-3.2-1B-Instruct-onnx-ryzenai-npu -d .\ci-cache oga-load --device npu --dtype int4 llm-prompt -p "Alice and Bob" --max-new-tokens 10
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

          # Test high-level APIs
          conda run -p .\lemon-ryzenai-ci python examples/api_oga_npu.py
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          conda run -p .\lemon-ryzenai-ci python examples/api_oga_npu_streaming.py
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      - name: Run Hybrid tests
        shell: PowerShell
        env:
          HF_HOME: "${{ env.HF_HOME }}"
          LEMONADE_CACHE_DIR: ".\\ci-cache"
        run: |
          $ErrorActionPreference = "Stop"

          # Test CLI
          conda run -p .\lemon-ryzenai-ci lemonade -m -i amd/Llama-3.2-1B-Instruct-onnx-ryzenai-hybrid oga-load --device hybrid --dtype int4 llm-prompt -p "Alice and Bob" --max-new-tokens 10
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

          # Test high-level APIs
          conda run -p .\lemon-ryzenai-ci python examples/api_oga_hybrid.py
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          conda run -p .\lemon-ryzenai-ci python examples/api_oga_hybrid_streaming.py
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
